### ISSUE TITLE
please make it visible that --confirm this-will-erase-data does not really erase data

### ISSUE THREAD

**Issue by LocoLati** [Seagate/ToolBin#24]
### Please describe the feature/improvement you would like to see added.

SeaChest_Lite:  Latest version.

When using a so called "data destructive command" with the command line argument "--confirm this-will-erase-data" I expect that there will be at least some data erased.  
But when using "--setSectorSize" to change the sector size from 512e to 4Kn for the first time it happened that I made up my mind and changed back from 4Kn to 512e and voila: ALL my data was still there!
My suggestion: Please change the words "this-will-erase-data" to something else reflecting the fact that this command does not erase anything but just makes it inaccessible sometimes - maybe relying only that the OS will superpose another file system structure.

Thank You

PS: This is my first suggestion here, maybe it is not the right place. please redirect it if necessary.  Thanks

### Please explain why you think adding this feature/improvement is important.

A user not being aware that this command is not really destructive may run into problems because confidential data may be unwantedly exposed.  So that I feel there should be a clear warning.

**Comment by vonericsen** [comment]
Hi @LocoLati,
This is something we can work on. Sometimes the features implemented from the standard are not always clear if a data erase will happen or if previously written data will still be accessible. Often, the spec leaves some things like this up to the device manufacturer to decide and this can change between firmware versions and products.

I made a change in the latest version (on Seagate.com, but not pushed on this repo yet) that will erase the boot sector when doing the sector size change, so it will erase some data, but it will not erase the entire disk. The purpose of this small erase was to overwrite the fake MBR record put at the beginning of GPT disks to be backwards compatible with older OSs. When this MBR is read in Windows, the drive cannot be reformatted which was causing some problems for users.

In much older versions we had multiple confirmations depending on the operation, but they were a lot to type and it was suggested we simplify to this.
Maybe we need a `--confirm this-will-erase-data` and a `--confirm this-may-erase-data` depending on the operation being performed.

Do you think adding some text to the help for each operation to identify which operations will erase vs may erase would be helpful in addition to the separate confirmations?

**Comment by vonericsen** [comment]
In the latest tools updated to this repo (and I believe the previous release), we added the possible data erase confirmation as well as another warning for low-level reformatting (fast format, depopulate, etc) that was also needed.

I'm closing this for now, but please feel free to reopen this if you think we have more work to do on this issue.
