### ISSUE TITLE
format error - SeaChest_Release_3.5.2_03-29-2023__15-05-29.usbBootMaker

### ISSUE THREAD

**Issue by Theletha** [Seagate/ToolBin#34]
### Problem

can't format the drive via the program to continue, outputting error 164
![image](https://github.com/Seagate/ToolBin/assets/10131942/6999c32a-f228-4de4-83bf-ccdfe15cbc66)

### Expected behavior

format

### How to reproduce

try to press create

### Deployment information

win 11 x64 

### Additional information

tried 4gb, 8gb and 16gb stick but all give same issue 
the software is from: ExosX24-Summit-ISE-SATA-512E-SE04.zip

**Comment by vonericsen** [comment]
Hi @Theletha,

Can you give me some details about the USB sticks you've tried?

Do you have a brand or model?

Were these USB drives previously formatted with a different file system (for example exfat or NTFS)?

Are you able to format them through Windows? You can do this by going into "This PC" then right clicking on the drive and selecting "Format". That will pop up a window where you can select file system, name, and other information to format with.

**Comment by Theletha** [comment]
Tried Kingston sticks. I tried to pre format all before the installer tried exfat, ntfs, fat32 but no go.

**Comment by vonericsen** [comment]
@Theletha,

We are attempting to recreate this issue internally to debug it but have not been able to get this error so far.

Does this error also happen with the SeaTools bootable USB found here: https://www.seagate.com/support/downloads/seatools/

**Comment by vonericsen** [comment]
@Theletha,

We have been debugging and we think we have found the cause of the error and have been able to recreate the issue.
I will update this issue when the package has been updated on the Seagate.com site

**Comment by Theletha** [comment]
Great news!
