### ISSUE TITLE
ST12000NM0007 won't allow fastFormat to 4k from 512e

### ISSUE THREAD

**Issue by mrfuzzemz** [Seagate/ToolBin#4]
Let me know if you need any other information.
Thanks!

> root: ./SeaChest_Format_120_1177_64 --formatUnit 4096 --fastFormat 1 --confirm I-understand-this-command-will-erase-all-data-on-the-drive -d /dev/sdp
> 
>  SeaChest_Format - Seagate drive utilities
>  Copyright (c) 2014-2017 Seagate Technology LLC and/or its Affiliates, All Rights Reserved
>  SeaChest_Format Version: 1.2.0-1_17_7 X86_64
>  Build Date: Nov  2 2017
>  Today: Tue Jan 23 16:18:50 2018
> 
> 
> sg17 - ST12000NM0007-2A1101 - ZJV00AN7 - ATA
> Format Unit
> Format Unit Not Supported or invalid option combination provided!

**Comment by rudock1** [comment]
--fastFormat is specifically for SAS interface drives and is used in conjunction with the --formatUnit command.  SATA interface drives can quickly change between logical sector sizes using the --setSectorSize command.

> --setSectorSize [new sector size]        (Seagate Only)
> This option is only available for drives that support sector size changes. On SATA Drives, the Set Sector Configuration command must be supported. On SAS Drives, Fast Format must be supported. A format unit can be used on SAS instead of this option to perform a long format and adjust sector size. Use the --showSupportedSectorSizes option to see the sector sizes the drive reports supporting. If this option doesn't list anything, please consult your product manual. This option should be used to quickly change between 5xxE and 4xxx sector sizes. Using this option to change from 512 to 520 or similar is not recommended at this time due to limited drive support.
> 
> This option can be used to quickly change the the logical sector size between 5xx emulation and 4xxx native logical block sizes. Resulting LBA (sector) count is either /8 or *8 the current Read Capacity or Identify, depending on the direction of the conversion.  In the case of SAS, this is a fast format unit command keeping existing data in the physical sector. The media may be readable, but data may be unspecified or may return errors on read access according to it's error processing algorithms.
