### ISSUE TITLE
SeaChest vs. openSeaChest Clarification

### ISSUE THREAD

**Issue by edrozenberg** [Seagate/ToolBin#6]
I'm curious if there's any reason to prefer one over the other set of utilities?

Currently I see the openSeaChest utilities are newer versions than the SeaChest utilities.

I also see a few differences in the list of utilities:
- _Logs only available in openSeaChest
- _Lite only available in SeaChest
- _Security only available in SeaChest
- _ZBD only available in openSeaChest

I also see the separate top-level directory "openSeaChest_LogParser", not sure if that's different from "_Logs" in openSeaChest.

I'm not much troubled by which to use :) because I anyway only need to use _Format for changing my 12TB SAS drives from 512E to 4Kn.

**Comment by rudock1** [comment]
Hi Eduard,

Thanks for checking out openSeaChest and doing such an accurate comparison between the open source and our "corporate" versions.

I would estimate the features are about 95% equal between the two sets.  There is also a lot of overlap between the tools themselves which is easy to see on this features list: https://github.com/Seagate/ToolBin/blob/master/SeaChest/SeaChestFeatures.18-Oct-2018.pdf.

Usually, the Seagate corporate versions are more up-to-date in our GitHub "toolbin" than the compiled openSeaChest binaries. The Windows SeaChest EXEs are certificate signed by Seagate. The complete collection of SeaChest tools, including a USB boot maker tool to run under Tiny Core Linux, is available on the Seagate website at https://www.seagate.com/support/software/seachest/.

Your comparison of differences is correct on all points. Part of that has to do with Seagate's own technical support is not connected with the openSeaChest project.

openSeaChest_Logs pulls unreadable binary logs of various types from the drives.  openSeaChest_LogParser is a tool to humanize the data into various readable formats.  The open source logs puller and parser are works in progress and have a ways to go before they are both in sync with each other,

I hope this covers your questions.  We really appreciate your time to check it all out. So cool you did that. Thanks again, and please feel free to keep the discussion going.

- Billy
